name: 'test-workflow'
on:
  workflow_run:
    workflows: [test-pr-workflow]
    types: [completed]

jobs:
  check-pull-request:
    # Check labels and author
    if: >-
      ${{
        github.event.workflow_run.conclusion == 'success'
      }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Check
        id: check_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo
            console.log('owner: ' + owner)
            console.log('repo: ' + repo)

            console.log('github.event.workflow_run: ' + ${{ github.event.workflow_run}})

            core.info(JSON.stringify(context.payload))

      - name: Next step
        if: success()
        run: echo 'Success! Hello World!'
