name: 'test-workflow'
on:
  workflow_run:
    workflows: [test-pr-workflow]
    types: [completed]

jobs:
  check-pull-request:
    if: >-
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.actor.login == vars.AUTHORIZED_USER
      }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Check label and commit count and author
        id: check_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get PR details
            const pull = await github.rest.pulls.get({
              owner: context.repo.owner
              repo: context.repo.repo
              pull_number: context.payload.workflow_run.pull_requests[0].number
            })

            // Check
            if (!pull.data.labels.map(label => label.name).includes('auto/merge')) {
              core.setFailed('This PR does not have the auto/merge label.')
            } else if (pull.data.commits != 1) {
              core.setFailed('This PR does not just one commit.')
            }

      - name: Next step
        if: success()
        run: echo 'Success! Hello World!'
