name: 'test-pr-workflow'
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Hello World PR
        run: echo 'Hello World! PR!'